# Uncomment this line to define a global platform for your project
platform :ios, "8.0"

target "PagueMenos" do

pod 'MBProgressHUD', '~> 0.9'
pod 'FontAwesome+iOS', '~> 0.1'


end

target "PagueMenosTests" do

end

