//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagueMenos.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class brand_owner
    {
        public int OWNER_CD { get; set; }
        public string OWNER_NM { get; set; }
        public string OWNER_LINK { get; set; }
        public string OWNER_WIKI_EN { get; set; }
    }
}
