//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagueMenos.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class brand_owner_bsin
    {
        public string BSIN { get; set; }
        public Nullable<int> OWNER_CD { get; set; }
    }
}
