//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagueMenos.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class gs1_gcp
    {
        public string GCP_CD { get; set; }
        public string GLN_CD { get; set; }
        public string GLN_NM { get; set; }
        public string GLN_ADDR_02 { get; set; }
        public string GLN_ADDR_03 { get; set; }
        public string GLN_ADDR_04 { get; set; }
        public string GLN_ADDR_POSTALCODE { get; set; }
        public string GLN_ADDR_CITY { get; set; }
        public string GLN_COUNTRY_ISO_CD { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACT_TEL { get; set; }
        public string CONTACT_HOTLINE { get; set; }
        public string CONTACT_FAX { get; set; }
        public string CONTACT_MAIL { get; set; }
        public string CONTACT_WEB { get; set; }
        public string GLN_LAST_CHANGE { get; set; }
        public string GLN_PROVIDER { get; set; }
        public string SEARCH_GTIN_CD { get; set; }
        public string GEPIR_GCP_CD { get; set; }
        public string ADD_PARTY_ID { get; set; }
        public string RETURN_CODE { get; set; }
        public string SOURCE { get; set; }
        public Nullable<System.DateTime> SYNC_DT { get; set; }
    }
}
