//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagueMenos.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class gs1_gpc
    {
        public string GPC_LANG { get; set; }
        public string GPC_CD { get; set; }
        public string GPC_NM { get; set; }
        public string GPC_LEVEL { get; set; }
        public string SOURCE { get; set; }
    }
}
