//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagueMenos.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class gs1_gpc_hier
    {
        public string GPC_S_CD { get; set; }
        public string GPC_F_CD { get; set; }
        public string GPC_C_CD { get; set; }
        public string GPC_B_CD { get; set; }
    }
}
