//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagueMenos.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class gs1_prefix
    {
        public string PREFIX_CD { get; set; }
        public string PREFIX_NM { get; set; }
        public string COUNTRY_ISO_CD { get; set; }
    }
}
