//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagueMenos.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class gs1_gcp_rc
    {
        public int RETURN_CODE { get; set; }
        public string RETURN_NAME { get; set; }
        public string ORIGIN { get; set; }
    }
}
