//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagueMenos.DataAccess.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PagueMenosEntities : DbContext
    {
        public PagueMenosEntities()
            : base("name=PagueMenosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<brand> brand { get; set; }
        public DbSet<brand_group> brand_group { get; set; }
        public DbSet<brand_owner> brand_owner { get; set; }
        public DbSet<brand_owner_bsin> brand_owner_bsin { get; set; }
        public DbSet<brand_type> brand_type { get; set; }
        public DbSet<gs1_gcp> gs1_gcp { get; set; }
        public DbSet<gs1_gcp_nb> gs1_gcp_nb { get; set; }
        public DbSet<gs1_gcp_rc> gs1_gcp_rc { get; set; }
        public DbSet<gs1_gpc> gs1_gpc { get; set; }
        public DbSet<gs1_gpc_hier> gs1_gpc_hier { get; set; }
        public DbSet<gs1_prefix> gs1_prefix { get; set; }
        public DbSet<gtin> gtin { get; set; }
        public DbSet<label> label { get; set; }
        public DbSet<nutrition_us> nutrition_us { get; set; }
        public DbSet<pkg_type> pkg_type { get; set; }
        public DbSet<label_gtin> label_gtin { get; set; }
    }
}
